### ISSUE TITLE
Enhancement:

### ISSUE THREAD

**Issue by s9iper1** [byteShaft/bidding-service#15]
single Ad details enhancement:
provide seller username 
provide seller review

**Comment by s9iper1** [comment]
priority based

**Comment by om26er** [comment]
reviews: https://github.com/om26er/bidding-service/commit/6aa38191a739b1b0a31d5d5a6123453d09a2028a

username: https://github.com/om26er/bidding-service/commit/1a1bc46a58c55a05c0e03a7ec260a4dca9d9410f
